name: nexkart6
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.1
  flutter_spinkit: ^5.2.1
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  photo_view: ^0.15.0
  razorpay_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ink
      fonts:
        - asset: assets/fonts/Ink.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
          weight: 400
    - family: L-Bold
      fonts: 
        - asset: assets/fonts/L-Bold.ttf
          weight: 700
    - family: LeagueSpartan-Regular
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
          weight: 400
    - family: MAGNETOB
      fonts:
        - asset: assets/fonts/MAGNETOB .TTF
          weight: 700
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
