const List<Map<String, dynamic>> products = [
  {
    'name': 'iPhone 15',
    'price': 79999,
    'oldPrice': 89999,
    'discount': 11,
    'brand': 'Apple',
    'image': 'assets/images/iphone_14_pro.png',
    'images': [
      'assets/images/iphone_14_pro.png',
      'assets/images/iphone_14_pro.png',
      'assets/images/iphone_14_pro.png',
    ],
    'rating': 4.7,
    'reviews': 1500,
    'stock': true,
    'isNew': true,
  },
  {
    'name': 'Galaxy S24',
    'price': 69999,
    'oldPrice': 79999,
    'discount': 13,
    'brand': 'Samsung',
    'image': 'assets/images/iphone8_mobile_dual_side.png',
    'images': [
      'assets/images/iphone_14_pro.png',
      'assets/images/iphone_14_pro.png',
      'assets/images/iphone_14_pro.png',
    ],
    'rating': 4.5,
    'reviews': 1200,
    'stock': true,
    'isNew': false,
  },
  {
    'name': 'MacBook Pro',
    'price': 129999,
    'oldPrice': 149999,
    'discount': 13,
    'brand': 'Apple',
    'image': 'assets/images/leather_jacket_4.png',
    'images': [
      'assets/images/iphone_14_pro.png',
      'assets/images/iphone_14_pro.png',
      'assets/images/iphone_14_pro.png',
    ],
    'rating': 4.8,
    'reviews': 800,
    'stock': false,
    'isNew': true,
  },
  {
    'name': 'Sony Headphones',
    'price': 9999,
    'oldPrice': 12999,
    'discount': 23,
    'brand': 'Sony',
    'image': 'assets/images/acer_laptop_var_4.png',
    'images': [
      'assets/images/iphone_14_pro.png',
      'assets/images/iphone_14_pro.png',
      'assets/images/iphone_14_pro.png',
    ],
    'rating': 4.3,
    'reviews': 600,
    'stock': true,
    'isNew': false,
  },
];
